import { NextResponse } from "next/server";
import { requireUserApi } from "@/lib/auth-utils";
import { prisma } from "@/lib/db";
import { generateGroceryNeeds, groupByCategory } from "@/lib/grocery-generator";
import { getUsageForecasts } from "@/lib/usage-forecast";
import { getWeekStart, addDays, parseDateOnly, slugify } from "@/lib/utils";

export async function GET(req: Request) {
  const user = await requireUserApi();
  if (user instanceof NextResponse) return user;
  const { searchParams } = new URL(req.url);
  const weekStartParam = searchParams.get("weekStart");

  const weekStart = weekStartParam
    ? parseDateOnly(weekStartParam)
    : getWeekStart();

  const list = await prisma.groceryList.findFirst({
    where: {
      householdId: user.householdId,
      weekStartDate: weekStart,
    },
    include: {
      items: {
        include: { ingredient: { include: { category: true } } },
        orderBy: { ingredient: { name: "asc" } },
      },
    },
  });

  if (!list) {
    return NextResponse.json({ items: [], lastGeneratedAt: null });
  }

  return NextResponse.json({
    ...list,
    lastGeneratedAt: list.lastGeneratedAt?.toISOString() ?? null,
  });
}

export async function POST(req: Request) {
  const user = await requireUserApi();
  if (user instanceof NextResponse) return user;
  const body = await req.json();
  const weekStart = body.weekStart
    ? parseDateOnly(body.weekStart)
    : getWeekStart();
  const weekEnd = addDays(weekStart, 6);

  const [mealEntries, pantry, staples, forecasts] = await Promise.all([
    prisma.mealPlanEntry.findMany({
      where: {
        householdId: user.householdId,
        date: { gte: weekStart, lte: weekEnd },
      },
      include: {
        recipe: {
          include: {
            recipeIngredients: {
              include: { ingredient: { include: { category: true } } },
            },
          },
        },
      },
    }),
    prisma.pantryItem.findMany({
      where: { householdId: user.householdId },
      include: { ingredient: { include: { category: true } } },
    }),
    prisma.recurringStaple.findMany({
      where: { householdId: user.householdId },
      include: { ingredient: { include: { category: true } } },
    }),
    getUsageForecasts(user.householdId),
  ]);

  const recipes = mealEntries.map((e) => e.recipe);
  const needs = generateGroceryNeeds(recipes, pantry);
  const autoGeneratedIds = new Set(needs.map((n) => n.ingredientId));

  for (const staple of staples) {
    const inPantry = pantry.find((p) => p.ingredientId === staple.ingredientId);
    const inNeeds = needs.find((n) => n.ingredientId === staple.ingredientId);
    const pantryQty = inPantry?.quantity ?? 0;

    if (pantryQty < staple.quantity) {
      const deficit = staple.quantity - pantryQty;
      if (inNeeds) {
        inNeeds.totalQuantity = Math.max(inNeeds.totalQuantity, deficit);
      } else {
        needs.push({
          ingredientId: staple.ingredientId,
          name: staple.ingredient.name,
          unit: staple.unit,
          categoryName: staple.ingredient.category.name,
          categorySlug: staple.ingredient.category.slug,
          totalQuantity: deficit,
        });
        autoGeneratedIds.add(staple.ingredientId);
      }
    }
  }

  for (const f of forecasts) {
    if (!f.isLowStock || f.suggestedBuy <= 0) continue;
    const inNeeds = needs.find((n) => n.ingredientId === f.ingredientId);
    if (inNeeds) {
      inNeeds.totalQuantity = Math.max(inNeeds.totalQuantity, f.suggestedBuy);
    } else {
      needs.push({
        ingredientId: f.ingredientId,
        name: f.name,
        unit: f.unit,
        categoryName: f.categoryName,
        categorySlug: slugify(f.categoryName),
        totalQuantity: f.suggestedBuy,
      });
    }
  }

  const grouped = groupByCategory(needs);

  let groceryList = await prisma.groceryList.findFirst({
    where: { householdId: user.householdId, weekStartDate: weekStart },
  });

  if (groceryList) {
    await prisma.groceryListItem.deleteMany({
      where: {
        groceryListId: groceryList.id,
        source: { in: ["AUTO_GENERATED", "LOW_STOCK"] },
      },
    });
  } else {
    groceryList = await prisma.groceryList.create({
      data: {
        householdId: user.householdId,
        weekStartDate: weekStart,
        status: "ACTIVE",
      },
    });
  }

  for (const need of needs) {
    const source = autoGeneratedIds.has(need.ingredientId)
      ? "AUTO_GENERATED"
      : "LOW_STOCK";

    await prisma.groceryListItem.upsert({
      where: {
        groceryListId_ingredientId: {
          groceryListId: groceryList.id,
          ingredientId: need.ingredientId,
        },
      },
      update: {
        quantity: need.totalQuantity,
        unit: need.unit,
        source,
      },
      create: {
        groceryListId: groceryList.id,
        ingredientId: need.ingredientId,
        quantity: need.totalQuantity,
        unit: need.unit,
        source,
      },
    });
  }

  await prisma.groceryList.update({
    where: { id: groceryList.id },
    data: { lastGeneratedAt: new Date() },
  });

  const fullList = await prisma.groceryList.findUnique({
    where: { id: groceryList.id },
    include: {
      items: {
        include: { ingredient: { include: { category: true } } },
      },
    },
  });

  return NextResponse.json(
    {
      list: fullList
        ? {
            ...fullList,
            lastGeneratedAt: fullList.lastGeneratedAt?.toISOString() ?? null,
          }
        : null,
      grouped,
    },
    { status: 201 }
  );
}

export async function PATCH(req: Request) {
  const user = await requireUserApi();
  if (user instanceof NextResponse) return user;
  const body = await req.json();
  const { itemId, checked, quantity, unit } = body;

  const item = await prisma.groceryListItem.findFirst({
    where: { id: itemId },
    include: { groceryList: true },
  });

  if (!item || item.groceryList.householdId !== user.householdId) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  if ((quantity !== undefined || unit !== undefined) && item.source !== "MANUAL") {
    return NextResponse.json(
      { error: "Only manually added items can be edited" },
      { status: 400 }
    );
  }

  const updated = await prisma.groceryListItem.update({
    where: { id: itemId },
    data: {
      ...(checked !== undefined && { checked }),
      ...(quantity !== undefined && { quantity }),
      ...(unit !== undefined && { unit }),
    },
    include: { ingredient: { include: { category: true } } },
  });

  return NextResponse.json(updated);
}
